version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.36
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 16686:16686
      - 6831:6831/udp
  testapp:
    build: .
    ports:
      - 8000:8000
